[package]
name = "reth-optimism-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "OP primitive types"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives = { workspace = true, features = ["optimism"] }
reth-primitives-traits.workspace = true
reth-codecs = { workspace = true, optional = true }

# op-reth
reth-optimism-consensus.workspace = true
reth-optimism-chainspec.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true

# codecs
modular-bitfield = { workspace = true, optional = true }
zstd = { workspace = true, optional = true }
serde.workspace = true

# misc
derive_more = { workspace = true, default-features = false, features = ["deref"] }

[features]
default = ["std", "reth-codec"]
std = ["reth-primitives-traits/std"]
reth-codec = ["dep:reth-codecs", "dep:zstd", "dep:modular-bitfield", "std"]